<?php

namespace Acme\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findAllOrderedByPrice(){
        return $this->getEntityManager()->createQuery(
                'SELECT p FROM Acme\TestBundle\Entity\Product p'
                )
                ->getResult();
                
    }
}
